/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#F6F8FC',
        surface: '#FFFFFF',
        'surface-bright': '#FFFFFF',
        'surface-dim': '#EEF2F9',
        'surface-variant': '#E9EEF8',
        'surface-container': '#FFFFFF',
        'surface-container-low': '#FBFCFF',
        'surface-container-lowest': '#F6F8FC',
        'surface-container-high': '#F8FAFF',
        'surface-container-highest': '#F2F5FC',
        primary: '#2F4BFF',
        'primary-container': '#DCE3FF',
        secondary: '#334155',
        tertiary: '#6B7280',
        'tertiary-container': '#E5E7EB',
        success: '#00C896',
        error: '#FF4B4B',
        'error-container': '#FFF0F0',
        outline: '#D1D5DB',
        'outline-variant': '#E5E7EB',
        'on-background': '#131620',
        'on-surface': '#131620',
        'on-surface-variant': '#6B7280',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#1F3277',
        'on-secondary': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'on-error': '#FFFFFF',
        'inverse-surface': '#111827',
        'inverse-primary': '#AAB8FF',
        'dark-bg': '#F6F8FC',
        'dark-surface': '#FFFFFF',
        'dark-border': '#E5E7EB',
        'dark-muted': '#6B7280',
        'accent-indigo': '#2F4BFF',
        'accent-red': '#FF4B4B',
        'accent-amber': '#F59E0B',
        'accent-emerald': '#00C896',
      },
      fontFamily: {
        sans: ['Satoshi', 'Inter', 'system-ui', 'sans-serif'],
        headline: ['"Cabinet Grotesk"', '"Space Grotesk"', 'sans-serif'],
        body: ['Satoshi', 'Inter', 'system-ui', 'sans-serif'],
        label: ['Satoshi', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        subtle: '0 4px 12px rgba(19, 22, 32, 0.04)',
        glow: '0 12px 32px rgba(47, 75, 255, 0.12)',
        ambient: '0 16px 40px rgba(19, 22, 32, 0.08)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
  darkMode: 'class',
}
